### ISSUE TITLE
FoodEffects Events don't like me and my gaming skills max pro

### ISSUE THREAD

**Issue by Klouver-github** [infernalexp/Food-Effects#2]
```
[06Nov2021 19:18:05.825] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID b486bbd1-b08b-4b68-bf89-2a2964300549
[06Nov2021 19:18:05.866] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$44893/1521006290.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.ClassCastException: net.minecraft.entity.merchant.villager.WanderingTraderEntity cannot be cast to net.minecraft.entity.player.PlayerEntity
	at org.infernalstudios.foodeffects.FoodEffectsEvents.onLivingEntityUseItemFinish(FoodEffectsEvents.java:50) ~[?:1.0.1]
	at net.minecraftforge.eventbus.ASMEventHandler_3456_FoodEffectsEvents_onLivingEntityUseItemFinish_Finish.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2671/1293826454.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.event.ForgeEventFactory.onItemUseFinish(ForgeEventFactory.java:325) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_71036_o(LivingEntity.java:2844) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_184608_ct(LivingEntity.java:2724) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2114) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.server.ServerWorld$$Lambda$46430/1280119345.accept(Unknown Source) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 6 more
```

**Comment by SwanX1** [comment]
bro put this in a paste link or at the very least upload the file

**Comment by Klouver-github** [comment]
sorry I thought the paste.gg posted: https://paste.gg/p/anonymous/0bc8d479be124e59ae08d5f5094d135d

**Comment by SwanX1** [comment]
bro who wrote this code and why is it so broken

**Comment by Klouver-github** [comment]
I am not sure which mod or code it is, but forge team told me it was your teams mod

**Comment by SwanX1** [comment]
yeah it's our mod, just fixed it and released an update for it
please update

**Comment by Klouver-github** [comment]
thanks Swan :)
